// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type RememberToken struct {
	ID            int64
	Selector      string
	ValidatorHash string
	UserID        int64
	CreatedAt     sql.NullString
	ExpiresAt     string
}

type Session struct {
	ID        int64
	UserID    int64
	SessionID string
	CreatedAt sql.NullString
	ExpiresAt string
}

type User struct {
	ID        int64
	Email     string
	Password  string
	Metadata  string
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}
