// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createRememberToken = `-- name: CreateRememberToken :exec
INSERT INTO remember_tokens (user_id, selector, validator_hash, expires_at)
VALUES (?, ?, ?, ?)
`

type CreateRememberTokenParams struct {
	UserID        int64
	Selector      string
	ValidatorHash string
	ExpiresAt     string
}

func (q *Queries) CreateRememberToken(ctx context.Context, arg CreateRememberTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRememberToken,
		arg.UserID,
		arg.Selector,
		arg.ValidatorHash,
		arg.ExpiresAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (user_id, session_id, expires_at)
VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	UserID    int64
	SessionID string
	ExpiresAt string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.UserID, arg.SessionID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one

INSERT INTO user (email, password, metadata)
VALUES (?, ?, ?)
RETURNING id
`

type CreateUserParams struct {
	Email    string
	Password string
	Metadata string
}

// Queries for User Management
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Password, arg.Metadata)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAllUserRememberTokens = `-- name: DeleteAllUserRememberTokens :exec
DELETE FROM remember_tokens
WHERE user_id = ?
`

func (q *Queries) DeleteAllUserRememberTokens(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllUserRememberTokens, userID)
	return err
}

const deleteAllUserSessions = `-- name: DeleteAllUserSessions :exec
DELETE FROM sessions
WHERE user_id = ?
`

func (q *Queries) DeleteAllUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllUserSessions, userID)
	return err
}

const deleteRememberTokenBySelector = `-- name: DeleteRememberTokenBySelector :exec
DELETE FROM remember_tokens
WHERE selector = ?
`

func (q *Queries) DeleteRememberTokenBySelector(ctx context.Context, selector string) error {
	_, err := q.db.ExecContext(ctx, deleteRememberTokenBySelector, selector)
	return err
}

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM sessions
WHERE session_id = ?
`

func (q *Queries) DeleteSessionByID(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByID, sessionID)
	return err
}

const getUserAndValidatorBySelector = `-- name: GetUserAndValidatorBySelector :one
SELECT u.id, u.email, u.password, u.metadata, u.created_at, u.updated_at, r.validator_hash
FROM user u
         JOIN remember_tokens r ON u.id = r.user_id
WHERE r.selector = ?
  AND r.expires_at > datetime('now')
`

type GetUserAndValidatorBySelectorRow struct {
	ID            int64
	Email         string
	Password      string
	Metadata      string
	CreatedAt     sql.NullString
	UpdatedAt     sql.NullString
	ValidatorHash string
}

func (q *Queries) GetUserAndValidatorBySelector(ctx context.Context, selector string) (GetUserAndValidatorBySelectorRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAndValidatorBySelector, selector)
	var i GetUserAndValidatorBySelectorRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ValidatorHash,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, metadata, created_at, updated_at
FROM user
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password, metadata, created_at, updated_at
FROM user
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBySessionID = `-- name: GetUserBySessionID :one
SELECT u.id, u.email, u.password, u.metadata, u.created_at, u.updated_at
FROM user u
         JOIN sessions t ON u.id = t.user_id
WHERE t.session_id = ?
  AND t.expires_at > datetime('now')
`

func (q *Queries) GetUserBySessionID(ctx context.Context, sessionID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySessionID, sessionID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rotateRememberToken = `-- name: RotateRememberToken :exec
UPDATE remember_tokens
SET validator_hash = ?,
    expires_at = ?
WHERE selector = ?
`

type RotateRememberTokenParams struct {
	ValidatorHash string
	ExpiresAt     string
	Selector      string
}

func (q *Queries) RotateRememberToken(ctx context.Context, arg RotateRememberTokenParams) error {
	_, err := q.db.ExecContext(ctx, rotateRememberToken, arg.ValidatorHash, arg.ExpiresAt, arg.Selector)
	return err
}

const updateUserMetadata = `-- name: UpdateUserMetadata :exec
UPDATE user SET metadata = json_patch(COALESCE(metadata, '{}'), ?) WHERE id = ?
`

type UpdateUserMetadataParams struct {
	JsonPatch interface{}
	ID        int64
}

func (q *Queries) UpdateUserMetadata(ctx context.Context, arg UpdateUserMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateUserMetadata, arg.JsonPatch, arg.ID)
	return err
}
